### ISSUE TITLE
Crytosign authentication

### ISSUE THREAD

**Issue by fabricetiennette** [Copterdoctor/SwiftWAMP#3]
Does your library implement Crytosign authentication?

**Comment by Copterdoctor** [comment]
Could you give some more info on what you're looking for?

WSS is supported by Starscream which handles the socket communication but I haven't implemented the ability to allow for self signed certificates yet.

**Comment by fabricetiennette** [comment]
Just want to know if your library implement crytosign authentication

https://crossbar.io/docs/Cryptosign-Authentication/

**Comment by Copterdoctor** [comment]
Oh ok WAMP Cryptosign instead of CRA. No I haven't implemented this feature but I can add it to the todo list.
